model_path: models/xgb_model.sav
thresholds: { low: 0.33, high: 0.66 }
messages:
  low: "ความเสี่ยงต่ำ: เฝ้าสังเกตอาการทั่วไป ล้างมือ สวมหน้ากากในที่แออัด"
  medium: "ความเสี่ยงปานกลาง: แนะนำตรวจ ATK ภายใน 24 ชม. และหลีกเลี่ยงใกล้ชิดผู้อื่น"
  high: "ความเสี่ยงสูง: ควรตรวจ ATK ทันทีและกักตัว รอดูผล/ปรึกษาแพทย์"
